"""sys_dictionary table turn to created_at updated_at

Revision ID: 0c051f553c7f
Revises: b1cdcd60ce58
Create Date: 2024-10-10 03:35:13.361479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c051f553c7f'
down_revision: Union[str, None] = 'b1cdcd60ce58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_dictionary_entry', 'createdAt', new_column_name='created_at')
    op.alter_column('sys_dictionary_entry', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_dictionary_entry', 'created_at',  new_column_name='createdAt')
    op.alter_column('sys_dictionary_entry', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
