"""news table 

Revision ID: 25a3b6879a46
Revises: fcbd16bc58cd
Create Date: 2024-10-09 21:51:03.929683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a3b6879a46'
down_revision: Union[str, None] = 'fcbd16bc58cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'viewCount', new_column_name='view_count', type_=sa.Integer(), nullable=False)
    op.alter_column('news', 'publishedAt', new_column_name='published_at', type_=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'view_count', new_column_name='viewCount', type_=sa.INTEGER(), server_default=sa.text('0'), nullable=False)
    op.alter_column('news', 'published_at', new_column_name='publishedAt', type_=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###
