"""docs feed_back table turn to created_at updated_at

Revision ID: 302650d4fde8
Revises: d42bb54ff1ed
Create Date: 2024-10-10 17:11:02.492224

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '302650d4fde8'
down_revision: Union[str, None] = 'd42bb54ff1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_back', 'createdAt', new_column_name='created_at')
    op.alter_column('feed_back', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_back', 'created_at',  new_column_name='createdAt')
    op.alter_column('feed_back', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
