"""delete changelog userId

Revision ID: 316816ffc578
Revises: 644478f0d5a9
Create Date: 2024-10-18 04:32:01.958109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316816ffc578'
down_revision: Union[str, None] = '644478f0d5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('change_log', 'userId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_log', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('change_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
