"""loginlog table add created_at updated_at

Revision ID: 3ea0ecba057c
Revises: dfc98ed7fe56
Create Date: 2024-10-10 01:03:18.901539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea0ecba057c'
down_revision: Union[str, None] = 'dfc98ed7fe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_loginlog', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sys_loginlog', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_loginlog', 'updated_at')
    op.drop_column('sys_loginlog', 'created_at')
    # ### end Alembic commands ###
