"""news table and news_category  table add created_at updated_at

Revision ID: 3eca1ae3d607
Revises: c5dd31e708cb
Create Date: 2024-10-10 00:42:51.575088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eca1ae3d607'
down_revision: Union[str, None] = 'c5dd31e708cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('news', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('news_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_category', 'updated_at')
    op.drop_column('news_category', 'created_at')
    op.drop_column('news', 'updated_at')
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###
