"""storage table turn to created_at updated_at

Revision ID: 622d6ce1333d
Revises: 3ea0ecba057c
Create Date: 2024-10-10 01:10:22.088677

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '622d6ce1333d'
down_revision: Union[str, None] = '3ea0ecba057c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools_storage', 'createdAt', new_column_name='created_at')
    op.alter_column('tools_storage', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools_storage', 'created_at',  new_column_name='createdAt')
    op.alter_column('tools_storage', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
