"""changelog user_id

Revision ID: 644478f0d5a9
Revises: 100de9d11e61
Create Date: 2024-10-18 04:16:24.982519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644478f0d5a9'
down_revision: Union[str, None] = '100de9d11e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_log', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_log', 'user_id')
    # ### end Alembic commands ###
