"""sys_menu table turn to created_at updated_at

Revision ID: 74045195b519
Revises: f73c8cb0fdac
Create Date: 2024-10-10 03:13:54.857720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74045195b519'
down_revision: Union[str, None] = 'f73c8cb0fdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_menu', 'createdAt', new_column_name='created_at')
    op.alter_column('sys_menu', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_menu', 'created_at',  new_column_name='createdAt')
    op.alter_column('sys_menu', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
