"""profile link table and profile_link_category  table add created_at updated_at

Revision ID: 743d6d16a737
Revises: 3eca1ae3d607
Create Date: 2024-10-10 00:45:28.096561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743d6d16a737'
down_revision: Union[str, None] = '3eca1ae3d607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_link', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_link', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profile_link_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('profile_link_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_link_category', 'updated_at')
    op.drop_column('profile_link_category', 'created_at')
    op.drop_column('profile_link', 'updated_at')
    op.drop_column('profile_link', 'created_at')
    # ### end Alembic commands ###
