"""blog_category table created_at updated_at

Revision ID: 9d3dc66cffc7
Revises: 25a3b6879a46
Create Date: 2024-10-09 22:55:42.418382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3dc66cffc7'
down_revision: Union[str, None] = '25a3b6879a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('blog_category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_category', 'updated_at')
    op.drop_column('blog_category', 'created_at')
    # ### end Alembic commands ###
