"""sys_dictionary table turn to created_at updated_at

Revision ID: b1cdcd60ce58
Revises: 74045195b519
Create Date: 2024-10-10 03:32:39.254515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1cdcd60ce58'
down_revision: Union[str, None] = '74045195b519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_dictionary', 'createdAt', new_column_name='created_at')
    op.alter_column('sys_dictionary', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_dictionary', 'created_at',  new_column_name='createdAt')
    op.alter_column('sys_dictionary', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
