"""blog table view_count published_at

Revision ID: c1ac06466c60
Revises: 662632f4d89d
Create Date: 2024-10-09 17:58:21.787157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1ac06466c60'
down_revision: Union[str, None] = '662632f4d89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'viewCount', new_column_name='view_count', type_=sa.Integer(), nullable=False)
    op.alter_column('blog', 'publishedAt', new_column_name='published_at', type_=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'view_count', new_column_name='viewCount', type_=sa.INTEGER(), server_default=sa.text('0'), nullable=False)
    op.alter_column('blog', 'published_at', new_column_name='publishedAt', type_=postgresql.TIMESTAMP(timezone=True), nullable=False)
    # ### end Alembic commands ###
