"""user sign logtable turn to created_at updated_at

Revision ID: d42bb54ff1ed
Revises: 510a9b2e0530
Create Date: 2024-10-10 17:08:22.192734

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42bb54ff1ed'
down_revision: Union[str, None] = '510a9b2e0530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sign_log', 'createdAt', new_column_name='created_at')
    op.alter_column('user_sign_log', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sign_log', 'created_at',  new_column_name='createdAt')
    op.alter_column('user_sign_log', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
