"""mail table add created_at updated_at

Revision ID: dfc98ed7fe56
Revises: 743d6d16a737
Create Date: 2024-10-10 01:01:57.831460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc98ed7fe56'
down_revision: Union[str, None] = '743d6d16a737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('mail', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail', 'updated_at')
    op.drop_column('mail', 'created_at')
    # ### end Alembic commands ###
