"""docs changelog table turn to created_at updated_at

Revision ID: e0997ddb12c1
Revises: 302650d4fde8
Create Date: 2024-10-10 17:14:27.261746

"""
from typing import Sequence, Union

from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0997ddb12c1'
down_revision: Union[str, None] = '302650d4fde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_log', 'createdAt', new_column_name='created_at')
    op.alter_column('change_log', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('change_log', 'created_at',  new_column_name='createdAt')
    op.alter_column('change_log', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
