"""link user_id

Revision ID: eb638e415585
Revises: bc9fc74fd682
Create Date: 2024-10-16 05:46:44.707619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb638e415585'
down_revision: Union[str, None] = 'bc9fc74fd682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_link', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_link', 'user_id')
    # ### end Alembic commands ###
