"""sys_role table turn to created_at updated_at

Revision ID: f73c8cb0fdac
Revises: c351184a87a2
Create Date: 2024-10-10 03:09:09.618756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f73c8cb0fdac'
down_revision: Union[str, None] = 'c351184a87a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_role', 'createdAt', new_column_name='created_at')
    op.alter_column('sys_role', 'updatedAt',  new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_role', 'created_at',  new_column_name='createdAt')
    op.alter_column('sys_role', 'updated_at',  new_column_name='updatedAt')
    # ### end Alembic commands ###
