/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClientImport } from './routes/_client'
import { Route as AdminImport } from './routes/_admin'
import { Route as ClientIndexImport } from './routes/_client/index'
import { Route as ClientNewsImport } from './routes/_client/news'
import { Route as ClientBlogImport } from './routes/_client/blog'
import { Route as ClientAboutImport } from './routes/_client/about'
import { Route as authAdminLoginImport } from './routes/(auth)/admin.login'

// Create/Update Routes

const ClientRoute = ClientImport.update({
  id: '/_client',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const ClientIndexRoute = ClientIndexImport.update({
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)

const ClientNewsRoute = ClientNewsImport.update({
  path: '/news',
  getParentRoute: () => ClientRoute,
} as any)

const ClientBlogRoute = ClientBlogImport.update({
  path: '/blog',
  getParentRoute: () => ClientRoute,
} as any)

const ClientAboutRoute = ClientAboutImport.update({
  path: '/about',
  getParentRoute: () => ClientRoute,
} as any)

const authAdminLoginRoute = authAdminLoginImport.update({
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClientImport
      parentRoute: typeof rootRoute
    }
    '/_client/about': {
      id: '/_client/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ClientAboutImport
      parentRoute: typeof ClientImport
    }
    '/_client/blog': {
      id: '/_client/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof ClientBlogImport
      parentRoute: typeof ClientImport
    }
    '/_client/news': {
      id: '/_client/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof ClientNewsImport
      parentRoute: typeof ClientImport
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexImport
      parentRoute: typeof ClientImport
    }
    '/(auth)/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof authAdminLoginImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ClientRouteChildren {
  ClientAboutRoute: typeof ClientAboutRoute
  ClientBlogRoute: typeof ClientBlogRoute
  ClientNewsRoute: typeof ClientNewsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAboutRoute: ClientAboutRoute,
  ClientBlogRoute: ClientBlogRoute,
  ClientNewsRoute: ClientNewsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof ClientRouteWithChildren
  '/about': typeof ClientAboutRoute
  '/blog': typeof ClientBlogRoute
  '/news': typeof ClientNewsRoute
  '/': typeof ClientIndexRoute
  '/admin/login': typeof authAdminLoginRoute
}

export interface FileRoutesByTo {
  '': typeof AdminRoute
  '/about': typeof ClientAboutRoute
  '/blog': typeof ClientBlogRoute
  '/news': typeof ClientNewsRoute
  '/': typeof ClientIndexRoute
  '/admin/login': typeof authAdminLoginRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_admin': typeof AdminRoute
  '/_client': typeof ClientRouteWithChildren
  '/_client/about': typeof ClientAboutRoute
  '/_client/blog': typeof ClientBlogRoute
  '/_client/news': typeof ClientNewsRoute
  '/_client/': typeof ClientIndexRoute
  '/admin/login': typeof authAdminLoginRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/blog' | '/news' | '/' | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/blog' | '/news' | '/' | '/admin/login'
  id:
    | '__root__'
    | '/_admin'
    | '/_client'
    | '/_client/about'
    | '/_client/blog'
    | '/_client/news'
    | '/_client/'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  ClientRoute: typeof ClientRouteWithChildren
  authAdminLoginRoute: typeof authAdminLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  ClientRoute: ClientRouteWithChildren,
  authAdminLoginRoute: authAdminLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_admin",
        "/_client",
        "/admin/login"
      ]
    },
    "/_admin": {
      "filePath": "_admin.tsx"
    },
    "/_client": {
      "filePath": "_client.tsx",
      "children": [
        "/_client/about",
        "/_client/blog",
        "/_client/news",
        "/_client/"
      ]
    },
    "/_client/about": {
      "filePath": "_client/about.tsx",
      "parent": "/_client"
    },
    "/_client/blog": {
      "filePath": "_client/blog.tsx",
      "parent": "/_client"
    },
    "/_client/news": {
      "filePath": "_client/news.tsx",
      "parent": "/_client"
    },
    "/_client/": {
      "filePath": "_client/index.tsx",
      "parent": "/_client"
    },
    "/admin/login": {
      "filePath": "(auth)/admin.login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
